### PR TITLE
Update mypy to 1.10.1

### PR DESCRIPTION
**Pull request by meghprkh**
Steps followed for future reference:

```bash
podman pull python:3.8-alpine
podman run -v .:/workspace:rw -it python:3.8-alpine /bin/sh

# In docker

/ # python --version
Python 3.8.19
/ # pip install pip-tools
/ # cd /workspace/
/workspace # pip-compile --generate-hashes ./requirements.in
```

### CODE REVIEW

**Comment by meghprkh** [comment]
@microsoft-github-policy-service agree

**Review by karthiknadig — DISMISSED** [review]

**Comment by meghprkh** [comment]
Just looked there is a version `1.10.1` probably makes sense to upgrade to that directly

**Comment by karthiknadig** [comment]
Go ahead and make the update.

**Comment by karthiknadig** [comment]
Can you generate the requirements using Python 3.8. This is to ensure package compatibility with minimum 3.8.

**Review by karthiknadig — APPROVED** [review]

**Review by eleanorjboyd — APPROVED** [review]

**Pull request merged**
