### PR TITLE
Add support for mypy `note`s

### PR DESCRIPTION
**Pull request by vidhanio**
support mypy notes.

this was previously broken due to the regex not supporting `note`s, as it required the `[code]` at the end (which notes do not have).

i also added a method of accumulating notes so that they don't span over multiple diagnostics, and instead are attached as one `note` diagnostic.

it also automatically finds `See <url>` lines in `note` diagnostics and attaches them in the code description.

also fixed the regex to exclude the two spaces before a `[code]`, and merged both the regexes into one.

image

### CODE REVIEW

**Comment by vidhanio** [comment]
@microsoft-github-policy-service agree

**Comment by karthiknadig** [comment]
@vidhanio Thanks for implementing this feature. Can you update the tests for this?

**Review by karthiknadig — DISMISSED** [review]

**Comment by vidhanio** [comment]
@karthiknadig i added some extra tests for the `note` feature.

**Comment by vidhanio** [comment]
interesting. mypy running on python 3.7 seems to not support error ends, and it is just a single character which gets selected. should the tests be split based on version then?

`== 3.7`:
```
testdir/__init__.py:2:22:2:22: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
testdir/__init__.py:2:22:2:22: note: This violates the Liskov substitution principle
testdir/__init__.py:2:22:2:22: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
testdir/__init__.py:2:22:2:22: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
testdir/__init__.py:2:22:2:22: note:     def __eq__(self, other: object) -> bool:
testdir/__init__.py:2:22:2:22: note:         if not isinstance(other, Foo):
testdir/__init__.py:2:22:2:22: note:             return NotImplemented
testdir/__init__.py:2:22:2:22: note:         return <logic to compare two Foo instances>
```
image

> **Note**
> It seems that VScode automatically turns 0-length ranges into just selecting the nearest ident, which causes the behaviour above.

`> 3.7`:
```
testdir/__init__.py:2:22:2:33: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
testdir/__init__.py:2:22:2:33: note: This violates the Liskov substitution principle
testdir/__init__.py:2:22:2:33: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
testdir/__init__.py:2:22:2:33: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
testdir/__init__.py:2:22:2:33: note:     def __eq__(self, other: object) -> bool:
testdir/__init__.py:2:22:2:33: note:         if not isinstance(other, Foo):
testdir/__init__.py:2:22:2:33: note:             return NotImplemented
testdir/__init__.py:2:22:2:33: note:         return <logic to compare two Foo instances>
```
image

**Comment by vidhanio** [comment]
@karthiknadig - i've tested locally, and this works on 3.11 and 3.7. could the checks be ran again and could this get another review? :)

**Review by karthiknadig — APPROVED** [review]

**Review by anthonykim1 — APPROVED** [review]

**Pull request merged**
