### PR TITLE
fix: usage of `deprecated` version of `Node.js`

### LINKED ISSUE #308: `codeql-analysis.yml` uses an action that uses a `deprecated` version of `Node.js`

### PR DESCRIPTION
**Pull request by meghprkh**
Fixes #308

### CODE REVIEW

**Review by karthiknadig — APPROVED** [review]

**Review by alexr00 — APPROVED** [review]

**Comment by meghprkh** [comment]
The idea here is to force-push and remove the conflicting commit [25fa7ec](https://github.com/microsoft/vscode-mypy/commit/25fa7ec8a7d56c9722a67d21d5a26f32ebc6feee) and merge #311 and #313 in order as both dont conflict.

**Review by anthonykim1 — APPROVED** [review]

**Comment by eleanorjboyd** [comment]
@karthiknadig any idea why this isn't able to merge?

**Comment by karthiknadig** [comment]
@eleanorjboyd Yes. I need to remove this commit [25fa7ec](https://github.com/microsoft/vscode-mypy/commit/25fa7ec8a7d56c9722a67d21d5a26f32ebc6feee)

**Comment by karthiknadig** [comment]
Due to org policy we can't force push to main. I will create a combined PR that takes commits from #311 and #313, and ensure that the contribution is correctly attributed in the release.

**Pull request closed without merging**
